### ISSUE TITLE
服务器metrics采集报错

### ISSUE THREAD

**Issue by chinarenliwei** [didi/KnowAgent#20]
服务版本：
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
cat /proc/version 
Linux version 5.4.155-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)) #1 SMP Mon Oct 18 17:53:28 EDT 2021

报错信息：
1、
Caused by: java.lang.NumberFormatException: For input string: "plist-sz"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_121]
	at com.didichuxing.datachannel.system.metrcis.service.linux.LinuxSystemMetricsServiceImpl.getSystemLoad1Only(LinuxSystemMetricsServiceImpl.java:565) ~[system-metrcis-1.0.0.jar:?]

2、
Caused by: java.lang.NumberFormatException: For input string: "ldavg-1"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_121]
	at com.didichuxing.datachannel.system.metrcis.service.linux.LinuxSystemMetricsServiceImpl.getSystemLoad5Only(LinuxSystemMetricsServiceImpl.java:589) ~[system-metrcis-1.0.0.jar:?]

3、
Caused by: java.lang.NumberFormatException: For input string: "ldavg-5"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_121]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_121]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_121]
	at com.didichuxing.datachannel.system.metrcis.service.linux.LinuxSystemMetricsServiceImpl.getSystemLoad15Only(LinuxSystemMetricsServiceImpl.java:613) ~[system-metrcis-1.0.0.jar:?]

问题原因：
LinuxSystemMetricsServiceImpl中的shell命令在本环境下查询到的内容如下：
sar -q 1 1 | grep ':' | awk '{print $4}'
plist-sz
2257
0.22
（其他两个报错类似）
LinuxSystemMetricsServiceImpl中的代码，使用了lines.get(0)

本地修改方式：
LinuxSystemMetricsServiceImpl代码中：
sar -q 1 1 | grep ':' | awk '{print $4}'               ==》             sar -q 1 1 | grep 'Average:' | awk '{print $4}' 
sar -q 1 1 | grep ':' | awk '{print $5}'               ==》             sar -q 1 1 | grep 'Average:' | awk '{print $5}' 
sar -q 1 1 | grep ':' | awk '{print $6}'               ==》             sar -q 1 1 | grep 'Average:' | awk '{print $6}'

**Comment by huqidong** [comment]
感谢你宝贵的建议与详细的错误信息描述，我们会在下一个版本中修复这些问题.
