### ISSUE TITLE
使用agent-manager的sh build.sh时，一致编译失败

### ISSUE THREAD

**Issue by zjy090** [didi/KnowAgent#44]
system-metrcis mvn clean install成功
但是使用agent-manager的sh build.sh时，出了很多的错误，单独进行npm install是正常的。
[INFO] ERROR in js/0.806a3df8490afc159ea4.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/1.396bec59f77a0c78971e.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/2.81037d357a8c0713d4f0.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/3.97a48913281c710806fd.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/4.5585632903a28726496c.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/5.4571949a8c779e162c14.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1409:36
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1405:32
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:9:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.seal (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1342:27)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:675:18
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1261:4
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:31:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\Hook.js:154:20)
[INFO]     at Compilation.finish (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1253:28)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compiler.js:672:17
[INFO]     at _done (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1185:12
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\webpack\lib\Compilation.js:1097:9
[INFO]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO]
[INFO] ERROR in js/agent.73ee07d6feac2ca44f16.js from Terser
[INFO] Error: error:0308010C:digital envelope routines::unsupported
[INFO]     at new Hash (node:internal/crypto/hash:69:19)
[INFO]     at Object.createHash (node:crypto:133:10)
[INFO]     at G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:217:37
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at TerserPlugin.optimizeFn (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\terser-webpack-plugin\dist\index.js:160:259)
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (G:\knowAgent\KnowAgent\agent-manager\agent-manager-console\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anony
mous>:12:1)

**Comment by huqidong** [comment]
nodejs & npm 什么版本呢？

**Comment by zjy090** [comment]
> nodejs & npm 什么版本呢？

18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 2
22 error Logi-AM@1.0.0 build: `cross-env NODE_OPTIONS=--max-old-space-size=8192 webpack --config webpack.prod.config.js`
22 error Exit status 2
23 error Failed at the Logi-AM@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

这个版本是通过pom.xml里配置产生的
 <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v12.20.0</nodeVersion>
              <npmVersion>6.14.8</npmVersion>
